[package]
name = "rtrb"
version = "0.1.0"
authors = ["Matthias Geier <Matthias.Geier@gmail.com>", "Stjepan Glavina <stjepang@gmail.com>"]
repository = "https://github.com/mgeier/rtrb"
edition = "2018"

[dependencies]
crossbeam-utils = "0.8.0"

[dev-dependencies]
rand = "0.7.3"
